// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package resourcebundle_lib.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import resourcebundle_lib.helpers.BundleHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_Translation_RetrieveDescription extends CustomJavaAction<java.lang.String>
{
	private IMendixObject Entity;
	private java.lang.String TranslationIdentifier;

	public JA_Translation_RetrieveDescription(IContext context, IMendixObject Entity, java.lang.String TranslationIdentifier)
	{
		super(context);
		this.Entity = Entity;
		this.TranslationIdentifier = TranslationIdentifier;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String key = String.valueOf(this.Entity.getId().toLong()) + BundleHelper.IDENTIFIER_DESCRIPTION;
		
		String translation = BundleHelper.getTranslationForKey(this.TranslationIdentifier, key, getContext());
		
		if (translation.isEmpty()) {
			BundleHelper.logger.warn("No translation found for object " + this.Entity.getType() + " with GUID " + key);
			return "";
		}
	
		return translation;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Translation_RetrieveDescription";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
